name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (TEST or PROD)"
        required: true
        type: choice
        options:
          - TEST
          - PROD

env:
  ENV_NAME: ${{ github.event.inputs.environment }}
  GOOGLE_APPLICATION_CREDENTIALS_PATH: ${{ github.workspace }}/gcloud.json

jobs:
  deploy-backend:
    name: Deploy Backend
    environment: ${{ github.event.inputs.environment }}-backend
    runs-on: ubuntu-latest
    steps:
      - name: Download Backend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-build-${{ github.event.inputs.environment }}
          path: ./server

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets[format('{0}_GOOGLE_APPLICATION_CREDENTIALS', github.event.inputs.environment)] }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > "$GOOGLE_APPLICATION_CREDENTIALS_PATH"

      - name: Deploy Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets[format('{0}_GOOGLE_APPLICATION_CREDENTIALS', github.event.inputs.environment)] }}
          FIREBASE_PROJECT_ID: ${{ secrets[format('{0}_FIREBASE_PROJECT_ID', github.event.inputs.environment)] }}
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS_PATH"
          firebase deploy --only functions --project "$FIREBASE_PROJECT_ID"
        working-directory: ./server

  deploy-frontend:
    name: Deploy Frontend
    environment: ${{ github.event.inputs.environment }}-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Download Frontend Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-${{ github.event.inputs.environment }}
          path: ./client

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets[format('{0}_GOOGLE_APPLICATION_CREDENTIALS', github.event.inputs.environment)] }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > "$GOOGLE_APPLICATION_CREDENTIALS_PATH"

      - name: Deploy Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets[format('{0}_GOOGLE_APPLICATION_CREDENTIALS', github.event.inputs.environment)] }}
          FIREBASE_PROJECT_ID: ${{ secrets[format('{0}_FIREBASE_PROJECT_ID', github.event.inputs.environment)] }}
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS_PATH"
          firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID"
        working-directory: ./client
