name: Build and Deploy

on:
  push:
    branches: [product]

env:
  PROJECT_ID: ${{ secrets.PROD_FIREBASE_PROJECT_ID }}
  GOOGLE_CREDENTIALS: ${{ secrets.PROD_GOOGLE_CREDENTIALS }}

jobs:
  changes:
    name: Check for Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'server/**'
            frontend:
              - 'client/**'

  build-deploy-frontend:
    name: Frontend
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: 📦 Install Dependencies and Build
        run: |
          npm ci
          npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.PROD_FIREBASE_API_KEY }}
          VITE_FIREBASE_PROJECT_ID: ${{ env.PROJECT_ID }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.PROD_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.PROD_FIREBASE_APP_ID }}
          VITE_CAPTCHA_SITE: ${{ secrets.PROD_CAPTCHA_SITE }}

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GOOGLE_CREDENTIALS }}

      - name: 📥 Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🚀 Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project ${{ github.ref_name }}

  build-deploy-backend:
    name: Backend
    runs-on: ubuntu-latest
    needs: changes
    if: true # ${{ needs.changes.outputs.backend == 'true' }}
    defaults:
      run:
        working-directory: ./server
    env:
      SERVICE_NAME: express-api
      REPOSITORY: gcf-artifacts
      REGION: us-central1
      IMAGE: us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/gcf-artifacts/express-api:latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Encode GOOGLE_CREDENTIALS to Base64
        id: encode_creds
        run: |
          echo "ENCODED_CREDS=$(echo '${{ secrets.GOOGLE_CREDENTIALS }}' | base64 -w 0)" >> $GITHUB_OUTPUT

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ env.GOOGLE_CREDENTIALS }}"

      - name: Set gcloud project
        run: gcloud config set project $PROJECT_ID

      - name: Authenticate Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Push Docker image to Artifact Registry
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --project $PROJECT_ID \
            --platform managed \
            --allow-unauthenticated \
            --ingress all \ 
            --set-env-vars ENVIRONMENT=production,TOKEN_SECRET=${{ secrets.PROD_TOKEN_SECRET }},CAPTCHA_SECRET=${{ secrets.PROD_CAPTCHA_SECRET }},DATABASE_URL=${{ secrets.PROD_DATABASE_URL }},GOOGLE_CREDENTIALS=${{ steps.encode_creds.outputs.ENCODED_CREDS }}
