name: Build and Deploy Product

on:
  push:
    branches: [product]

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Paths Changes Filter
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'server/**'
            frontend:
              - 'client/**'

  build-deploy-backend:
    name: Backend
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - run: npm ci && npm run build
        name: Build
        working-directory: ./server
      - run: |
          touch .env          
          echo ENVIRONMENT=production >> .env
          echo TOKEN_SECRET=${{ secrets.PROD_TOKEN_SECRET }} >> .env           
          echo DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} >> .env  
          echo CAPTCHA_SECRET=${{ secrets.PROD_CAPTCHA_SECRET }} >> .env        
          cat .env
        name: Create .env File
        working-directory: ./server
      - run: npm install -g firebase-tools
        name: Install Dependencies
      - run: firebase use --token ${{ secrets.FIREBASE_TOKEN }} product
        name: Set Project
      - run: firebase deploy --only functions --token ${{ secrets.FIREBASE_TOKEN }}
        name: Deploy

  build-deploy-frontend:
    name: Frontend
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - run: npm ci && npm run build
        name: Build
        working-directory: ./client
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.PROD_FIREBASE_API_KEY }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.PROD_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.PROD_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.PROD_FIREBASE_APP_ID }}
          VITE_CAPTCHA_SITE: ${{ secrets.PROD_CAPTCHA_SITE }}
      - run: npm install -g firebase-tools
        name: Install Dependencies
      - run: firebase use --token ${{ secrets.FIREBASE_TOKEN }} product
        name: Set Project
      - run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
        name: Deploy
